openapi: 3.0.0
info:
  title: ""
  version: 0.0.1
security: []
paths:
  /chunks:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    id: 1
                    hash: 040f06fd774092478d450774f5ba30c5da78acc8
                    metadata:
                      int: 1
                      bool: true
                      string: this is the text
                    pageContent: content
                    documentId: 1
                    documentIndex: 0
                    toolName: get_current_weather
                    userId: "1"
                properties:
                  id:
                    type: integer
                  hash:
                    type: string
                  metadata:
                    type: object
                    properties:
                      int:
                        type: integer
                      bool:
                        type: boolean
                      string:
                        type: string
                  pageContent:
                    type: string
                  documentId:
                    type: integer
                  documentIndex:
                    type: integer
                  toolName:
                    type: string
                  userId:
                    type: string
                  "":
                    type: string
                    x-stoplight:
                      id: 2w21ym9314di6
              examples:
                example_chunk_post_res_0:
                  value:
                    id: 1
                    hash: 040f06fd774092478d450774f5ba30c5da78acc8
                    metadata:
                      int: 1
                      bool: true
                      string: this is the text
                    pageContent: content
                    documentId: 1
                    documentIndex: 0
                    toolName: get_current_weather
                    userId: "1"
                example_chunk_post_res_0_error:
                  value:
                    name: BadRequest
                    message: Error resolving data
                    code: 400
                    className: bad-request
                    data:
                      embedding:
                        name: BadRequest
                        message: Hash 040f06fd774092478d450774f5ba30c5da78acc8 is not unique. Document already exists.
                        code: 400
                        className: bad-request
      operationId: get-chunks
      parameters: []
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    id: 1
                    hash: 040f06fd774092478d450774f5ba30c5da78acc8
                    metadata:
                      int: 1
                      bool: true
                      string: this is the text
                    pageContent: content
                    documentId: 1
                    documentIndex: 0
                    toolName: get_current_weather
                    userId: "1"
                properties:
                  id:
                    type: integer
                  hash:
                    type: string
                  metadata:
                    type: object
                    properties:
                      int:
                        type: integer
                      bool:
                        type: boolean
                      string:
                        type: string
                  pageContent:
                    type: string
                  documentId:
                    type: integer
                  documentIndex:
                    type: integer
                  toolName:
                    type: string
                  userId:
                    type: string
                  "":
                    type: string
                    x-stoplight:
                      id: 2w21ym9314di6
              examples:
                example_chunk_post_res_0:
                  value:
                    id: 1
                    hash: 040f06fd774092478d450774f5ba30c5da78acc8
                    metadata:
                      int: 1
                      bool: true
                      string: this is the text
                    pageContent: content
                    documentId: 1
                    documentIndex: 0
                    toolName: get_current_weather
                    userId: "1"
                example_chunk_post_res_0_error:
                  value:
                    name: BadRequest
                    message: Error resolving data
                    code: 400
                    className: bad-request
                    data:
                      embedding:
                        name: BadRequest
                        message: Hash 040f06fd774092478d450774f5ba30c5da78acc8 is not unique. Document already exists.
                        code: 400
                        className: bad-request
      operationId: post-chunks
      x-stoplight:
        id: 8720d54cclka4
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
              x-examples:
                Example 1:
                  metadata:
                    int: 1
                    bool: true
                    string: this is the text
                  pageContent: content
                  documentId: 1
                  documentIndex: 0
                  toolName: "{{tool_name}}"
            examples:
              example_chunk_post_req_0:
                value:
                  metadata:
                    int: 1
                    bool: true
                    string: this is the text
                  pageContent: content
                  documentId: 1
                  documentIndex: 0
                  toolName: "{{tool_name}}"
examples:
  chats_zero:

schemas:
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
        minimum: 0
      message:
        type: string
      name:
        type: string
      className:
        type: string
  IntegerId:
    type: integer
    readOnly: true
    minimum: 0
    maximum: 100000000
    example: 1
  Uuid:
    type: string
    format: uuid
    example: 74738ff5-5367-5958-9aee-98fffdcd1876
  ObjectId:
    anyOf:
      - type: string
        example: 74738ff5-5367-5958-9aee-98fffdcd1876
      - type: object
        properties: {}
        additionalProperties: false
  ISODate:
    type: string
    format: date-time
    example: "2017-07-21T17:32:28.000Z"
  Chunk:
    type: object
    x-examples:
      Example 1:
        id: 55
        hash: 040f06fd774092478d450774f5ba30c5da78acc8
        metadata:
          int: 1
          bool: true
          string: this is the text
        pageContent: content
        documentId: 1
        documentIndex: 0
        toolName: get_current_weather
        userId: "19"
    properties:
      id:
        type: integer
        readOnly: true
      hash:
        type: string
        readOnly: true
      metadata:
        type: object
      pageContent:
        type: string
      documentId:
        type: integer
      documentIndex:
        type: integer
      toolName:
        type: string
      userId:
        type: integer
        readOnly: true
      embedding:
        type: string
        x-stoplight:
          id: nvgaqhokkdrpv
        readOnly: true
